[project]
name = "aider-pilot"
version = "0.1.0"
description = "aider pilot"
authors = [
    {name = "Antonio Reid", email = "read.musik@gmail.com"},
]
dependencies = [
    "aider-install>=0.1.3",
    "tree-sitter>=0.24.0",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.pdm]
distribution = true

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "black>=25.1.0",
]
