name: autofix.ci
on:
  workflow_call:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      # Use uv to ensure we have the same ruff version in CI and locally.
      - uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231
        with:
          version: "0.4.20"
      # Fix lint errors
      - run: uv run ruff check --fix-only .
      # Format code
      - run: uv run ruff format .
      - uses: actions/setup-node@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
          run_install: false
    
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
  
      - name: Install dependencies
        run: pnpm install

      - name: Format with Prettier
        run: pnpm prettier --write .

      - uses: autofix-ci/action@v1.3.1
