name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # Required for turborepo
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4.2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22 # Updated to Node.js 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test # Add this step if you have tests