services:
  survey-backend:
    build:
      context: ./apps/survey-automation
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/survey-automation:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=:99
      - PYTHONPATH=/app
    networks:
      - survey-network
    restart: unless-stopped

  # VNC server for browser viewing
  vnc-server:
    image: theasp/novnc:latest
    ports:
      - "8080:8080"
    environment:
      - DISPLAY_WIDTH=1024
      - DISPLAY_HEIGHT=768
      - RUN_XTERM=no
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - survey-network
    depends_on:
      - survey-backend

networks:
  survey-network:
    driver: bridge
